name: JobFlow-API-Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t shivangm16/jobflow-api:latest .

      - name: Publish image to docker hub
        run: docker push shivangm16/jobflow-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

      - name: Pull docker-compose
        run: |
          curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Stop existing containers
        run: docker-compose down || true

      - name: Pull image from docker hub
        run: docker pull shivangm16/jobflow-api:latest

      - name: Start containers with docker-compose
        run: |
          docker-compose up -d

      - name: Health check
        run: |
          sleep 15
          curl http://localhost:5001/health || exit 1