-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "salary_max" SET DATA TYPE TEXT,
ALTER COLUMN "salary_min" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Tracked_Jobs" ALTER COLUMN "salary_max" SET DATA TYPE TEXT,
ALTER COLUMN "salary_min" SET DATA TYPE TEXT;
