name: JobFlow-API-Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker compose build

      - name: Push images to docker hub
        run: |
          docker tag jobflow-api:latest shivangm16/jobflow-api:latest
          docker push shivangm16/jobflow-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

      - name: Stop existing containers
        run: docker compose down || true

      - name: Pull latest images
        run: |
          docker pull shivangm16/jobflow-api:latest

      - name: Start containers with docker compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Health check
        run: |
          sleep 15  # Give the API time to start
          curl -f http://localhost:5001/api || exit 1

      - name: Clean up old images
        run: docker image prune -f
